### ISSUE TITLE
Should we make `switch` a keyword?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/tree-sitter-r#84]
Mostly for highlighting purposes. It would be specified the same as `return` where its a keyword even though its a function call

**Comment by kevinushey** [comment]
I would say yes, both because of existing precedent and because it's a primitive function with special evaluation rules?

It might be worth cataloguing the tokens we want to highlight as "special". The ones I can think of off the top of my head:

function return
if else for in while repeat break next
try tryCatch; maybe withCallingHandlers?
NULL TRUE FALSE Inf NaN NA NA_integer_ NA_real_ NA_character_ NA_complex_
